name: Build an image and push it to Docker Hub

on:
  push:
    branches: [main]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v4
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: ooxif/chisel:latest
